# Generated by Django 2.1.2 on 2018-10-27 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0)),
                ('data_ent', models.DateTimeField(verbose_name='data entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('total_estoque', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0)),
                ('data_sadia', models.DateTimeField(verbose_name='data saida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_estoque.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_estoque.Produto'),
        ),
    ]
