# Generated by Django 2.1.2 on 2018-11-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0004_auto_20181103_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='item_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
