# Generated by Django 2.1.2 on 2018-11-11 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0005_auto_20181103_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('situacao', models.CharField(choices=[('ENTRADA', 'entrada'), ('SAIDA', 'saida')], max_length=6, unique=True)),
                ('qtd', models.IntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_estoque.Produto')),
            ],
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='saida',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='Saida',
        ),
    ]
