# Generated by Django 2.1.2 on 2018-11-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0007_auto_20181110_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='situacao',
            field=models.CharField(choices=[('Entrada', 'entrada'), ('Saida', 'saida')], max_length=7),
        ),
    ]
