# Generated by Django 2.1.3 on 2018-12-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0008_auto_20181110_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='total_estoque',
        ),
    ]
