# Generated by Django 2.1.2 on 2018-11-02 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0002_auto_20181101_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='item_descricao',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
