# Generated by Django 3.1.7 on 2021-03-08 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0009_remove_produto_total_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='data_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
